### ISSUE TITLE
error C7510: invoke_result_t':

### ISSUE THREAD

**Issue by flaviu22** [PaulRitaldato1/ThreadPool#2]
Hello. I have tried to use your ThreadPool class in a test project, and I got the following error on compiling:

```
1>c:\project\threadpool\threadpool.h(50): error C7510: 'invoke_result_t': use of dependent type name must be prefixed with 'typename'
1>c:\project\threadpool\threadpool.h(50): note: This diagnostic occurred in the compiler generated function 'auto ThreadPool::enqueue(Func &&,Args &&...)'

```

The test was:

```
#include <iostream>
#include "ThreadPool.h"

int main()
{
    std::cout << "Hello World!\n";
	//

	return 0;
}

```
Can you take a look ? I build this on VS2017, Windows OS.

**Comment by PaulRitaldato1** [comment]
What C++ features are you compiling with? This should work with C++17 on MSVC++ 

Edit: Also, I tested this on VS2019 with C++17 feature set and it compiles with VS2019 C++20 feature set. You may need to upgrade you VS version, or C++ feature set

**Comment by PaulRitaldato1** [comment]
Tested by building with C++14, and got the same error. I am only supporting C++17 and later with this project
